// GENERATED by site/scripts/gen-packages.mjs — do not edit by hand.
// Source of truth: packages/*/package.json descriptions.

export type PackageCategory = "dom" | "server" | "ssr" | "cli" | "test" | "orm" | "logger" | "otel" | "core";

export interface PackageEntry {
  /** npm package name */
  name: string;
  /** directory under packages/ */
  dir: string;
  /** ecosystem bucket */
  cat: PackageCategory;
  /** package.json description */
  desc: string;
}

export const packages: PackageEntry[] = [
  {
    "name": "@youneed/ai-skill",
    "dir": "ai-skill",
    "cat": "core",
    "desc": "Agent Skills that turn Claude into a youneed-framework expert: the `youneed` skill (components, server, organization, performance, server-optimizations/security/best-practices, middleware, realtime/pub-sub, plugins & infra, a11y, i18n, auth/login (OAuth2/OTP/JWT/webhooks), migration) plus focused skills for the CLI framework (cli), server-side rendering & static generation (ssr), devtools/ts-plugin (develop), logger/transports/config (logging), orm-sql/kv (orm), writing/running tests (testing), migrating an existing app onto the youneed stack — frontend/backend/data/tests + build switch + interop adapters (migration), authorization + secrets (security), feature flags (feature-flags), application server plugins graphql/grpc/mailer/storage/queue/otlp (server-plugins), the shad UI library + component providers (ui), typed API client / resilient fetch / runtime adapters (clients), and the shared @youneed/core primitives + build tooling (foundation)."
  },
  {
    "name": "@youneed/api-client",
    "dir": "api-client",
    "cat": "core",
    "desc": "Typed API client runtime + OpenAPI → TypeScript client codegen (consumes the OpenAPI @youneed/server generates). Dependency-free, uses fetch (or @youneed/http-client)."
  },
  {
    "name": "@youneed/cli",
    "dir": "cli",
    "cat": "cli",
    "desc": "Type-safe, Commander-style CLI framework on the @youneed factory-class pattern."
  },
  {
    "name": "@youneed/cli-middleware-cache",
    "dir": "cli-middleware-cache",
    "cat": "cli",
    "desc": "Disk cache middleware: this.cache.get/set/wrap, TTL, JSON on disk."
  },
  {
    "name": "@youneed/cli-middleware-childprocess",
    "dir": "cli-middleware-childprocess",
    "cat": "cli",
    "desc": "Child-process middleware for @youneed/cli: this.childprocess.spawn / .exec wrap node:child_process in a task — reactive (pending/output/exit), killed on shutdown or teardown."
  },
  {
    "name": "@youneed/cli-middleware-clipboard",
    "dir": "cli-middleware-clipboard",
    "cat": "cli",
    "desc": "Clipboard middleware: this.clipboard.write/read via system clipboard."
  },
  {
    "name": "@youneed/cli-middleware-color",
    "dir": "cli-middleware-color",
    "cat": "cli",
    "desc": "Terminal color & styling middleware for @youneed/cli: adds this.color with ANSI styles, honouring NO_COLOR / --no-color / TTY detection."
  },
  {
    "name": "@youneed/cli-middleware-env",
    "dir": "cli-middleware-env",
    "cat": "cli",
    "desc": "Environment-variable middleware for @youneed/cli: adds a typed, validated this.env parsed from process.env via @youneed/schema, failing fast on bad config."
  },
  {
    "name": "@youneed/cli-middleware-fs",
    "dir": "cli-middleware-fs",
    "cat": "cli",
    "desc": "Filesystem middleware: this.fs read/write + temp dirs auto-removed on teardown."
  },
  {
    "name": "@youneed/cli-middleware-hotkeys",
    "dir": "cli-middleware-hotkeys",
    "cat": "cli",
    "desc": "Hotkey middleware: this.keys.on(name, handler) over the raw terminal."
  },
  {
    "name": "@youneed/cli-middleware-i18n",
    "dir": "cli-middleware-i18n",
    "cat": "cli",
    "desc": "i18n middleware for @youneed/cli: this.i18n (translate/locale) backed by @youneed/i18n."
  },
  {
    "name": "@youneed/cli-middleware-logger",
    "dir": "cli-middleware-logger",
    "cat": "cli",
    "desc": "Logger middleware for @youneed/cli: adds this.logger (a @youneed/logger instance) with level wired from --verbose/--quiet flags."
  },
  {
    "name": "@youneed/cli-middleware-markdown",
    "dir": "cli-middleware-markdown",
    "cat": "cli",
    "desc": "Markdown middleware: this.markdown(md) renders Markdown to terminal."
  },
  {
    "name": "@youneed/cli-middleware-music",
    "dir": "cli-middleware-music",
    "cat": "cli",
    "desc": "Music transport for @youneed/cli: adds this.player (track metadata + elapsed/duration/play/pause clock), with an optional system-player backend for real audio."
  },
  {
    "name": "@youneed/cli-middleware-notification",
    "dir": "cli-middleware-notification",
    "cat": "cli",
    "desc": "Desktop notification middleware for @youneed/cli: adds this.notify (send/info/success/warn/error) backed by node-notifier, with a graceful fallback when it isn't installed."
  },
  {
    "name": "@youneed/cli-middleware-oscillator",
    "dir": "cli-middleware-oscillator",
    "cat": "cli",
    "desc": "A synthetic spectrum source + cava-style bar renderer for @youneed/cli: adds this.oscillator and spectrumBars() for terminal audio visualisers."
  },
  {
    "name": "@youneed/cli-middleware-pages",
    "dir": "cli-middleware-pages",
    "cat": "cli",
    "desc": "Pager middleware: this.pages.show(text) pages long output."
  },
  {
    "name": "@youneed/cli-middleware-progress",
    "dir": "cli-middleware-progress",
    "cat": "cli",
    "desc": "Progress-bar middleware: this.progress.bar() with percent/ETA."
  },
  {
    "name": "@youneed/cli-middleware-prompt",
    "dir": "cli-middleware-prompt",
    "cat": "cli",
    "desc": "Interactive prompts for @youneed/cli: adds this.prompt with ask/confirm/choice/list/alert — raw-key TUI primitives drawn via the core live renderer."
  },
  {
    "name": "@youneed/cli-middleware-screen",
    "dir": "cli-middleware-screen",
    "cat": "cli",
    "desc": "Alternate-screen middleware: full-screen TUI buffer; restores on teardown."
  },
  {
    "name": "@youneed/cli-middleware-worker",
    "dir": "cli-middleware-worker",
    "cat": "cli",
    "desc": "Worker-thread middleware for @youneed/cli: this.worker.run / .spawn wrap node:worker_threads in a task — offload CPU work, reactive, terminated on shutdown or teardown."
  },
  {
    "name": "@youneed/cli-plugin-completion",
    "dir": "cli-plugin-completion",
    "cat": "cli",
    "desc": "Shell-completion plugin for @youneed/cli: registers a `completion` command that emits bash/zsh/fish scripts generated from the command catalogue."
  },
  {
    "name": "@youneed/cli-plugin-config",
    "dir": "cli-plugin-config",
    "cat": "cli",
    "desc": "Config-file plugin for @youneed/cli: loads a config file (rc / *.config.json / package.json field) and merges its values into option defaults app-wide."
  },
  {
    "name": "@youneed/cli-plugin-devtools",
    "dir": "cli-plugin-devtools",
    "cat": "cli",
    "desc": "Devtools server for @youneed/cli: serves the unified <youneed-devtools> shell (same UI as the server devtools) — a shad command/option builder that lists commands, fills in an invocation from a form, and copies or runs it over the devtools protocol."
  },
  {
    "name": "@youneed/cli-plugin-error",
    "dir": "cli-plugin-error",
    "cat": "cli",
    "desc": "Error-formatting plugin for @youneed/cli: pretty stderr output, hints, and optional stack traces via the onError lifecycle hook."
  },
  {
    "name": "@youneed/cli-plugin-feature-flags",
    "dir": "cli-plugin-feature-flags",
    "cat": "cli",
    "desc": "Feature-flag plugin for @youneed/cli: a `flags` command to list/inspect/override flags plus middleware that adds this.flags (isEnabled/variant/value/evaluate) so any command can gate behavior on a flag."
  },
  {
    "name": "@youneed/cli-plugin-help",
    "dir": "cli-plugin-help",
    "cat": "cli",
    "desc": "Enhanced help plugin: a richer help command with examples and grouped commands."
  },
  {
    "name": "@youneed/cli-plugin-man",
    "dir": "cli-plugin-man",
    "cat": "cli",
    "desc": "Man-page plugin: a man command emitting roff documentation from the catalogue."
  },
  {
    "name": "@youneed/cli-plugin-otel",
    "dir": "cli-plugin-otel",
    "cat": "otel",
    "desc": "@youneed/cli plugin + middleware: real OpenTelemetry SDK — a span per command execution, cli.command metrics, OTLP/HTTP export flushed before exit."
  },
  {
    "name": "@youneed/cli-plugin-update-notifier",
    "dir": "cli-plugin-update-notifier",
    "cat": "cli",
    "desc": "Update-notifier plugin: checks npm for a newer version, notifies after commands."
  },
  {
    "name": "@youneed/core",
    "dir": "core",
    "cat": "core",
    "desc": "Foundational primitives shared across @youneed packages: shared types, the class-metadata registry (TC39 addInitializer + WeakMap, esbuild/tsx-safe), and disposal helpers."
  },
  {
    "name": "create-youneedpackage",
    "dir": "create-package",
    "cat": "core",
    "desc": "Internal scaffolder for @youneed/* workspace packages."
  },
  {
    "name": "@youneed/devtools",
    "dir": "devtools",
    "cat": "dom",
    "desc": "Inspector panel (component tree, time-travel, schedulers) + Page devtools."
  },
  {
    "name": "@youneed/devtools-protocol",
    "dir": "devtools-protocol",
    "cat": "core",
    "desc": "Universal, CDP-style devtools protocol for every youneed surface (frontend, server, ssr, cli): JSON-RPC 2.0 envelopes, targets, domains, commands + events, pluggable transports, and a domain-keyed UI extension registry (one protocol, per-surface UI)."
  },
  {
    "name": "@youneed/dom",
    "dir": "dom",
    "cat": "dom",
    "desc": "Reactive components on native Custom Elements + Shadow DOM."
  },
  {
    "name": "@youneed/dom-adapter-angular",
    "dir": "dom-adapter-angular",
    "cat": "dom",
    "desc": "Use @youneed/dom components inside Angular and Angular components inside @youneed/dom — type-safe and refactor-friendly (pass the class, not a tag string)."
  },
  {
    "name": "@youneed/dom-adapter-astro",
    "dir": "dom-adapter-astro",
    "cat": "dom",
    "desc": "Render @youneed/dom components to SSR HTML for Astro islands — Declarative Shadow DOM + client hydration, type-safe (pass the component, not a tag string)."
  },
  {
    "name": "@youneed/dom-adapter-preact",
    "dir": "dom-adapter-preact",
    "cat": "dom",
    "desc": "Use @youneed/dom components inside Preact and Preact components inside @youneed/dom — type-safe and refactor-friendly (pass the component, not a tag string)."
  },
  {
    "name": "@youneed/dom-adapter-react",
    "dir": "dom-adapter-react",
    "cat": "dom",
    "desc": "Render @youneed/dom components inside React — type-safe and refactor-friendly (pass the class, not a tag string)."
  },
  {
    "name": "@youneed/dom-adapter-svelte",
    "dir": "dom-adapter-svelte",
    "cat": "dom",
    "desc": "Use @youneed/dom components inside Svelte (a use: action) and Svelte components inside @youneed/dom — type-safe and refactor-friendly (pass the component, not a tag string)."
  },
  {
    "name": "@youneed/dom-adapter-vue",
    "dir": "dom-adapter-vue",
    "cat": "dom",
    "desc": "Use @youneed/dom components inside Vue and Vue components inside @youneed/dom — type-safe and refactor-friendly (pass the component, not a tag string)."
  },
  {
    "name": "@youneed/dom-provider-a11y",
    "dir": "dom-provider-a11y",
    "cat": "dom",
    "desc": "Accessibility helpers for @youneed/dom components — a composable provider for screen-reader announcements, focus trapping, and reduced-motion."
  },
  {
    "name": "@youneed/dom-provider-color-scheme",
    "dir": "dom-provider-color-scheme",
    "cat": "dom",
    "desc": "Light/dark/auto color scheme for @youneed/dom — a composable provider that reflects CSS color-scheme globally or per component, toggled via this.setColorScheme."
  },
  {
    "name": "@youneed/dom-provider-direction",
    "dir": "dom-provider-direction",
    "cat": "dom",
    "desc": "Per-component text direction (LTR/RTL) for @youneed/dom: a composable provider that reflects `dir` and toggles via this.setDirection."
  },
  {
    "name": "@youneed/dom-provider-env",
    "dir": "dom-provider-env",
    "cat": "dom",
    "desc": "Type-safe, fail-fast environment variables for @youneed/dom — coerce + validate import.meta.env (or any source) against a @youneed/schema spec, read it via this.env, inspect it in devtools."
  },
  {
    "name": "@youneed/dom-provider-feature-flags",
    "dir": "dom-provider-feature-flags",
    "cat": "dom",
    "desc": "Use @youneed/feature-flags inside @youneed/dom components — evaluate flags in html templates with reactive re-render on flag change, plus SSR hydration."
  },
  {
    "name": "@youneed/dom-provider-i18n",
    "dir": "dom-provider-i18n",
    "cat": "dom",
    "desc": "Use @youneed/i18n translations inside @youneed/dom components — i18n() in html templates with reactive re-render on locale change."
  },
  {
    "name": "@youneed/dom-provider-logger",
    "dir": "dom-provider-logger",
    "cat": "dom",
    "desc": "A scoped @youneed/logger child on every @youneed/dom component — this.logger, stamped with the component tag, via a composable provider."
  },
  {
    "name": "@youneed/dom-provider-otel",
    "dir": "dom-provider-otel",
    "cat": "otel",
    "desc": "@youneed/dom provider: real OpenTelemetry Web SDK — render spans per component, dom.render metrics, OTLP/HTTP export flushed on pagehide."
  },
  {
    "name": "@youneed/dom-provider-rbac",
    "dir": "dom-provider-rbac",
    "cat": "dom",
    "desc": "Use @youneed/rbac inside @youneed/dom components — gate UI in html templates with `this.can(action, resource, instance?)`, re-rendering when the current subject changes."
  },
  {
    "name": "@youneed/dom-provider-timers",
    "dir": "dom-provider-timers",
    "cat": "dom",
    "desc": "Lifecycle-scoped timers for @youneed/dom — a composable provider contributing this.timers: setTimeout/setInterval/rAF/idle/delay + the Scheduler API (postTask, yield) + debounce/throttle, all auto-cancelled when the component disconnects."
  },
  {
    "name": "@youneed/dom-provider-virtual",
    "dir": "dom-provider-virtual",
    "cat": "dom",
    "desc": "Composable @youneed/dom provider for IntersectionObserver-driven list virtualization (this.virtual) — only visible chunks render."
  },
  {
    "name": "@youneed/dom-provider-zustand",
    "dir": "dom-provider-zustand",
    "cat": "dom",
    "desc": "Bind a Zustand store to @youneed/dom components — a composable provider for reactive this.store with optional selector-gated re-renders."
  },
  {
    "name": "@youneed/dom-router",
    "dir": "dom-router",
    "cat": "dom",
    "desc": "Tiny client-side SPA router (hash / history / query)."
  },
  {
    "name": "@youneed/dom-scheduler",
    "dir": "dom-scheduler",
    "cat": "dom",
    "desc": "Prioritized, batching render scheduler (DOM/Node-agnostic; rAF/idle with setTimeout fallback)."
  },
  {
    "name": "@youneed/dom-ui-shad",
    "dir": "dom-ui-shad",
    "cat": "dom",
    "desc": "shadcn-style component library on @youneed/dom (Custom Elements + Tailwind), with a copy-the-source CLI."
  },
  {
    "name": "@youneed/feature-flags",
    "dir": "feature-flags",
    "cat": "core",
    "desc": "Tiny framework-agnostic feature-flag engine: boolean/variant/value flags, attribute targeting + deterministic percentage rollout, synchronous evaluation, SSR snapshot hydration."
  },
  {
    "name": "@youneed/feature-flags-datadog",
    "dir": "feature-flags-datadog",
    "cat": "core",
    "desc": "Framework-agnostic @youneed/feature-flags adapter: batch flag EXPOSURES to the Datadog Logs intake (no Datadog SDK, plain fetch) via flags.onEvaluation."
  },
  {
    "name": "@youneed/feature-flags-launchdarkly",
    "dir": "feature-flags-launchdarkly",
    "cat": "core",
    "desc": "LaunchDarkly provider adapter for @youneed/feature-flags (Node server SDK-backed remote evaluator)."
  },
  {
    "name": "@youneed/feature-flags-posthog",
    "dir": "feature-flags-posthog",
    "cat": "core",
    "desc": "PostHog provider for @youneed/feature-flags — a framework-agnostic remote evaluator over PostHog's /decide HTTP API (no SDK, pure fetch)."
  },
  {
    "name": "@youneed/feature-flags-vercel",
    "dir": "feature-flags-vercel",
    "cat": "core",
    "desc": "Vercel Edge Config source for @youneed/feature-flags: pulls flag definitions from an Edge Config store (plain fetch, no SDK), with polling for live updates."
  },
  {
    "name": "@youneed/http-client",
    "dir": "http-client",
    "cat": "core",
    "desc": "Zero-dep resilient fetch: timeout, retry + backoff (honors Retry-After), and a circuit breaker."
  },
  {
    "name": "@youneed/i18n",
    "dir": "i18n",
    "cat": "core",
    "desc": "Tiny, fully-typed translation core: dotted-path keys with autocomplete, interpolation, locale switching, subscriptions."
  },
  {
    "name": "@youneed/kv",
    "dir": "kv",
    "cat": "server",
    "desc": "Back-compat alias for @youneed/server-plugin-store (the KV contract + MemoryKV)."
  },
  {
    "name": "@youneed/kv-redis",
    "dir": "kv-redis",
    "cat": "server",
    "desc": "Back-compat alias for @youneed/server-plugin-pubsub-redis (RedisKV + RedisPubSub)."
  },
  {
    "name": "@youneed/logger",
    "dir": "logger",
    "cat": "logger",
    "desc": "Zero-dep structured logger: levels, JSON lines, child bindings, secret redaction."
  },
  {
    "name": "@youneed/logger-plugin-datadog",
    "dir": "logger-plugin-datadog",
    "cat": "logger",
    "desc": "@youneed/logger plugin: stamp Datadog-standard default fields (ddsource/service/ddtags) on every record."
  },
  {
    "name": "@youneed/logger-plugin-exception",
    "dir": "logger-plugin-exception",
    "cat": "logger",
    "desc": "@youneed/logger plugin: log uncaughtException/unhandledRejection (Winston-style exception handlers)."
  },
  {
    "name": "@youneed/logger-plugin-i18n",
    "dir": "logger-plugin-i18n",
    "cat": "logger",
    "desc": "@youneed/logger plugin: translate log message keys through an @youneed/i18n translator at format time."
  },
  {
    "name": "@youneed/logger-plugin-location",
    "dir": "logger-plugin-location",
    "cat": "logger",
    "desc": "@youneed/logger plugin: stamp each record with the call site (file:line:column) it was logged from."
  },
  {
    "name": "@youneed/logger-plugin-otel",
    "dir": "logger-plugin-otel",
    "cat": "otel",
    "desc": "@youneed/logger plugin: stamp trace_id / span_id / trace_flags of the active OpenTelemetry span on every log record."
  },
  {
    "name": "@youneed/logger-transport-file",
    "dir": "logger-transport-file",
    "cat": "logger",
    "desc": "@youneed/logger transport: append log lines to a file (sync or buffered stream)."
  },
  {
    "name": "@youneed/logger-transport-http",
    "dir": "logger-transport-http",
    "cat": "logger",
    "desc": "@youneed/logger transport: batch-ship log records to an HTTP endpoint via fetch/sendBeacon (universal)."
  },
  {
    "name": "@youneed/logger-transport-stdout",
    "dir": "logger-transport-stdout",
    "cat": "logger",
    "desc": "@youneed/logger transport: fast Node process.stdout/stderr writer for high-throughput servers."
  },
  {
    "name": "@youneed/orm-adapter-mongo",
    "dir": "orm-adapter-mongo",
    "cat": "orm",
    "desc": "MongoDB adapter for @youneed/orm-nosql (official mongodb driver)."
  },
  {
    "name": "@youneed/orm-adapter-mysql",
    "dir": "orm-adapter-mysql",
    "cat": "orm",
    "desc": "MySQL adapter for @youneed/orm-sql (mysql2-backed)."
  },
  {
    "name": "@youneed/orm-adapter-postgres",
    "dir": "orm-adapter-postgres",
    "cat": "orm",
    "desc": "PostgreSQL adapter for @youneed/orm-sql (node-postgres/`pg`-backed)."
  },
  {
    "name": "@youneed/orm-nosql",
    "dir": "orm-nosql",
    "cat": "orm",
    "desc": "Tiny document/NoSQL ORM on standard TC39 decorators (Mongoose-style collections, Mongo-style query filters, pluggable document-store adapters; ships an in-memory store)."
  },
  {
    "name": "@youneed/orm-sql",
    "dir": "orm-sql",
    "cat": "orm",
    "desc": "Tiny SQL ORM on standard TC39 decorators (TypeORM-style entities, pluggable DB adapters)."
  },
  {
    "name": "@youneed/otel",
    "dir": "otel",
    "cat": "otel",
    "desc": "Shared OpenTelemetry setup for @youneed/* framework levels: real OTel SDK (node + web), OTLP/HTTP traces + metrics, W3C propagation helpers, instrumented fetch."
  },
  {
    "name": "@youneed/rbac",
    "dir": "rbac",
    "cat": "core",
    "desc": "Tiny framework-agnostic authorization engine: roles + permissions (action × resource), role inheritance, ownership/attribute conditions, deny-over-allow, synchronous can()."
  },
  {
    "name": "@youneed/schema",
    "dir": "schema",
    "cat": "core",
    "desc": "class-validator-style DTO validation on standard TC39 decorators (no reflect-metadata, works in JS)."
  },
  {
    "name": "@youneed/secrets",
    "dir": "secrets",
    "cat": "core",
    "desc": "Tiny framework-agnostic secrets manager: one SecretsProvider contract, caching, `secret://` reference resolution, env/memory/file built-ins; Vault & AWS adapters ship separately."
  },
  {
    "name": "@youneed/secrets-aws",
    "dir": "secrets-aws",
    "cat": "core",
    "desc": "AWS Secrets Manager provider for @youneed/secrets (pure fetch + SigV4, no aws-sdk)."
  },
  {
    "name": "@youneed/secrets-vault",
    "dir": "secrets-vault",
    "cat": "core",
    "desc": "HashiCorp Vault (KV v2) SecretsProvider for @youneed/secrets — pure fetch, no SDK."
  },
  {
    "name": "@youneed/server",
    "dir": "server",
    "cat": "server",
    "desc": "Tiny typed HTTP server (controllers, middleware, cache)."
  },
  {
    "name": "@youneed/server-adapter",
    "dir": "server-adapter",
    "cat": "server",
    "desc": "Run a @youneed/server app on any runtime: a Web `fetch` bridge (Bun / Deno / edge / Workers) over the app's Node request listener, plus node/bun/deno serve adapters."
  },
  {
    "name": "@youneed/server-middleware-accept-language",
    "dir": "server-middleware-accept-language",
    "cat": "server",
    "desc": "@youneed/server middleware: negotiate the request locale from the Accept-Language header (HTTP content negotiation)."
  },
  {
    "name": "@youneed/server-middleware-api-key",
    "dir": "server-middleware-api-key",
    "cat": "server",
    "desc": "@youneed/server middleware: shared-secret API key auth (header/query/scheme), SHA-256 matched, principal mapping."
  },
  {
    "name": "@youneed/server-middleware-authorization",
    "dir": "server-middleware-authorization",
    "cat": "server",
    "desc": "@youneed/server middleware: generic Authorization-header auth with a pluggable signing algorithm (bring your own sign/verify/generatePair) + self-contained signed tokens."
  },
  {
    "name": "@youneed/server-middleware-basic-auth",
    "dir": "server-middleware-basic-auth",
    "cat": "server",
    "desc": "@youneed/server middleware: HTTP Basic auth + API-key auth."
  },
  {
    "name": "@youneed/server-middleware-bearer",
    "dir": "server-middleware-bearer",
    "cat": "server",
    "desc": "@youneed/server middleware: Bearer-token authentication."
  },
  {
    "name": "@youneed/server-middleware-body-limit",
    "dir": "server-middleware-body-limit",
    "cat": "server",
    "desc": "@youneed/server middleware: reject oversized request bodies."
  },
  {
    "name": "@youneed/server-middleware-compression",
    "dir": "server-middleware-compression",
    "cat": "server",
    "desc": "@youneed/server middleware: gzip/brotli response compression."
  },
  {
    "name": "@youneed/server-middleware-cors",
    "dir": "server-middleware-cors",
    "cat": "server",
    "desc": "@youneed/server middleware: CORS headers + preflight."
  },
  {
    "name": "@youneed/server-middleware-csrf",
    "dir": "server-middleware-csrf",
    "cat": "server",
    "desc": "@youneed/server middleware: stateless CSRF (double-submit cookie)."
  },
  {
    "name": "@youneed/server-middleware-etag",
    "dir": "server-middleware-etag",
    "cat": "server",
    "desc": "@youneed/server middleware: ETag + conditional GET (304)."
  },
  {
    "name": "@youneed/server-middleware-health",
    "dir": "server-middleware-health",
    "cat": "server",
    "desc": "@youneed/server middleware: Kubernetes-style liveness/readiness probe endpoints."
  },
  {
    "name": "@youneed/server-middleware-helmet",
    "dir": "server-middleware-helmet",
    "cat": "server",
    "desc": "@youneed/server middleware: security response headers (helmet-style)."
  },
  {
    "name": "@youneed/server-middleware-http2-guard",
    "dir": "server-middleware-http2-guard",
    "cat": "server",
    "desc": "@youneed/server middleware: HTTP/2 DoS protection (Rapid Reset, stream floods)."
  },
  {
    "name": "@youneed/server-middleware-https-redirect",
    "dir": "server-middleware-https-redirect",
    "cat": "server",
    "desc": "@youneed/server middleware: force HTTPS + canonical host/trailing-slash redirects."
  },
  {
    "name": "@youneed/server-middleware-idempotency",
    "dir": "server-middleware-idempotency",
    "cat": "server",
    "desc": "@youneed/server middleware: Idempotency-Key — safe retries of unsafe requests via a pluggable KV store."
  },
  {
    "name": "@youneed/server-middleware-ip-filter",
    "dir": "server-middleware-ip-filter",
    "cat": "server",
    "desc": "@youneed/server middleware: allow/deny requests by client IP (CIDR, IPv4/IPv6), proxy-aware."
  },
  {
    "name": "@youneed/server-middleware-jwt",
    "dir": "server-middleware-jwt",
    "cat": "server",
    "desc": "@youneed/server middleware: JWT (JWS) authentication — verifies signature (HS/RS/PS/ES) + claims, with JWKS support. Zero dependencies."
  },
  {
    "name": "@youneed/server-middleware-keep-alive",
    "dir": "server-middleware-keep-alive",
    "cat": "server",
    "desc": "@youneed/server middleware: advertise a Keep-Alive header + drop connections programmatically."
  },
  {
    "name": "@youneed/server-middleware-load-shed",
    "dir": "server-middleware-load-shed",
    "cat": "server",
    "desc": "@youneed/server middleware: load-shedding (global concurrency limit) — fast-fail surplus requests with 503 under overload."
  },
  {
    "name": "@youneed/server-middleware-logger",
    "dir": "server-middleware-logger",
    "cat": "server",
    "desc": "@youneed/server middleware: attach a request-scoped @youneed/logger child (bound to requestId/traceId) — log(ctx)."
  },
  {
    "name": "@youneed/server-middleware-metrics",
    "dir": "server-middleware-metrics",
    "cat": "server",
    "desc": "@youneed/server middleware: dependency-free Prometheus metrics + /metrics exposition."
  },
  {
    "name": "@youneed/server-middleware-rate-limit",
    "dir": "server-middleware-rate-limit",
    "cat": "server",
    "desc": "@youneed/server middleware: rate limiting with pluggable strategies (fixed/sliding/token-bucket/exponential)."
  },
  {
    "name": "@youneed/server-middleware-request-id",
    "dir": "server-middleware-request-id",
    "cat": "server",
    "desc": "@youneed/server middleware: per-request correlation id (trusted inbound X-Request-Id or generated), echoed + log-correlated."
  },
  {
    "name": "@youneed/server-middleware-request-logger",
    "dir": "server-middleware-request-logger",
    "cat": "server",
    "desc": "@youneed/server middleware: per-request access logging."
  },
  {
    "name": "@youneed/server-middleware-server-timing",
    "dir": "server-middleware-server-timing",
    "cat": "server",
    "desc": "@youneed/server middleware: emit a Server-Timing response header (DevTools timings)."
  },
  {
    "name": "@youneed/server-middleware-session",
    "dir": "server-middleware-session",
    "cat": "server",
    "desc": "@youneed/server middleware: signed-cookie sessions with a pluggable store."
  },
  {
    "name": "@youneed/server-middleware-static",
    "dir": "server-middleware-static",
    "cat": "server",
    "desc": "@youneed/server middleware: serve static files from disk with HTTP Range, ETag, and conditional-request support."
  },
  {
    "name": "@youneed/server-middleware-timeout",
    "dir": "server-middleware-timeout",
    "cat": "server",
    "desc": "@youneed/server middleware: fail requests that exceed a deadline (503)."
  },
  {
    "name": "@youneed/server-middleware-trace",
    "dir": "server-middleware-trace",
    "cat": "server",
    "desc": "@youneed/server middleware: W3C traceparent distributed tracing (dependency-free, OpenTelemetry-compatible IDs)."
  },
  {
    "name": "@youneed/server-middleware-trust-proxy",
    "dir": "server-middleware-trust-proxy",
    "cat": "server",
    "desc": "@youneed/server middleware: resolve the real client IP/protocol/host from X-Forwarded-* headers behind a proxy/CDN."
  },
  {
    "name": "@youneed/server-middleware-webhook-signature",
    "dir": "server-middleware-webhook-signature",
    "cat": "server",
    "desc": "@youneed/server middleware: verify inbound webhook HMAC signatures over the raw body. Pure verify function + generic builder + per-provider subpaths (stripe/github/shopify)."
  },
  {
    "name": "@youneed/server-plugin-cluster",
    "dir": "server-plugin-cluster",
    "cat": "server",
    "desc": "@youneed/server plugin: multi-core supervisor — fork workers across CPUs, restart crashes, graceful drain on SIGTERM."
  },
  {
    "name": "@youneed/server-plugin-devtools",
    "dir": "server-plugin-devtools",
    "cat": "server",
    "desc": "@youneed/server plugin: dev-time topology, OWASP security audit, OpenAPI generation and microbenchmarks — mounts a devtools UI on a live app."
  },
  {
    "name": "@youneed/server-plugin-docker",
    "dir": "server-plugin-docker",
    "cat": "server",
    "desc": "Wrap a @youneed/server or SSR app in Docker: generate a Dockerfile + .dockerignore + docker-compose.yml, with backing services (Mongo/MySQL/Postgres/Redis) inferred from the app's mounted plugins. Ships a devtools tab to view the artifacts."
  },
  {
    "name": "@youneed/server-plugin-env",
    "dir": "server-plugin-env",
    "cat": "server",
    "desc": "Type-safe, fail-fast environment variables for @youneed/server — coerce + validate process.env against a @youneed/schema spec, with a devtools-visible ServerPlugin."
  },
  {
    "name": "@youneed/server-plugin-feature-flags",
    "dir": "server-plugin-feature-flags",
    "cat": "server",
    "desc": "@youneed/server plugin + controller provider for @youneed/feature-flags: request-scoped `this.flags`, a client-bootstrap snapshot route, dev override toggles, and a devtools Feature Flags tab."
  },
  {
    "name": "@youneed/server-plugin-graphql",
    "dir": "server-plugin-graphql",
    "cat": "server",
    "desc": "@youneed/server plugin: a spec-compliant GraphQL HTTP endpoint over graphql-js (schema-first SDL or programmatic schema, GraphiQL, resolvers, per-request context), with a devtools tab (playground, SDL viewer, recent ops)."
  },
  {
    "name": "@youneed/server-plugin-grpc",
    "dir": "server-plugin-grpc",
    "cat": "server",
    "desc": "@youneed/server plugin: run a gRPC (HTTP/2) server alongside your @youneed/server app on its lifecycle, with introspection + a unary call-tester over HTTP and a devtools tab."
  },
  {
    "name": "@youneed/server-plugin-jobs",
    "dir": "server-plugin-jobs",
    "cat": "server",
    "desc": "@youneed/server plugin: job scheduler (cron, intervals, delays) wired to the server lifecycle, with an optional KV leader-lock for fleets."
  },
  {
    "name": "@youneed/server-plugin-jsonrpc",
    "dir": "server-plugin-jsonrpc",
    "cat": "server",
    "desc": "JSON-RPC 2.0 for @youneed/server: class + TC39-decorator endpoints (@JsonRPC.method) with schema-validated params, served over a POST request or a Chrome-CDP-style WebSocket, plus a @youneed/server-plugin-devtools panel to inspect methods and debug calls."
  },
  {
    "name": "@youneed/server-plugin-kv",
    "dir": "server-plugin-kv",
    "cat": "server",
    "desc": "Mount a KV store (from @youneed/server-plugin-store) as a ServerPlugin for @youneed/server: tracks reads/writes/hit-rate + surfaces a live key browser in @youneed/server-plugin-devtools (Infra card, header tab, flow node). Re-exports the KV contract."
  },
  {
    "name": "@youneed/server-plugin-mailer",
    "dir": "server-plugin-mailer",
    "cat": "server",
    "desc": "@youneed/server plugin: transactional email with pluggable transports — built-in dependency-free SMTP plus AWS SES, SendGrid and Postmark (fetch-based, no SDKs), with a devtools tab."
  },
  {
    "name": "@youneed/server-plugin-oauth2",
    "dir": "server-plugin-oauth2",
    "cat": "server",
    "desc": "OAuth2/OIDC login (Authorization Code + PKCE) for @youneed/server: a ServerPlugin core + universal, named providers (github/google/facebook/yandex/vk) you can extend, plus Telegram Login Widget."
  },
  {
    "name": "@youneed/server-plugin-otel",
    "dir": "server-plugin-otel",
    "cat": "otel",
    "desc": "@youneed/server plugin + middleware: real OpenTelemetry SDK — SERVER spans per request with W3C propagation, http.server metrics, OTLP/HTTP export."
  },
  {
    "name": "@youneed/server-plugin-otlp",
    "dir": "server-plugin-otlp",
    "cat": "server",
    "desc": "@youneed/server plugin: export per-request traces over OTLP/HTTP (JSON) to an OpenTelemetry collector / Jaeger / Tempo — no OTel SDK — with a devtools tab."
  },
  {
    "name": "@youneed/server-plugin-otp",
    "dir": "server-plugin-otp",
    "cat": "server",
    "desc": "One-time-password login (passwordless / 2FA) for @youneed/server: a ServerPlugin core + pluggable channels — email (built-in SMTP) and SMS."
  },
  {
    "name": "@youneed/server-plugin-pubsub",
    "dir": "server-plugin-pubsub",
    "cat": "server",
    "desc": "Backend-agnostic publish/subscribe for @youneed/server: PubSub contract + MemoryPubSub + a ServerPlugin that surfaces channels in @youneed/server-plugin-devtools (flow graph, header tab, message sender). Re-exports the KV store."
  },
  {
    "name": "@youneed/server-plugin-pubsub-deno",
    "dir": "server-plugin-pubsub-deno",
    "cat": "server",
    "desc": "Deno KV adapter for @youneed/server-plugin-pubsub + -store: DenoKV and DenoPubSub (Deno KV queues). Runs on the Deno runtime / Deno Deploy."
  },
  {
    "name": "@youneed/server-plugin-pubsub-kafka",
    "dir": "server-plugin-pubsub-kafka",
    "cat": "server",
    "desc": "Kafka adapter for @youneed/server-plugin-pubsub: KafkaPubSub over topics, via the official `kafkajs`. Pub/sub only (pair with a KV adapter for state)."
  },
  {
    "name": "@youneed/server-plugin-pubsub-nats",
    "dir": "server-plugin-pubsub-nats",
    "cat": "server",
    "desc": "NATS adapter for @youneed/server-plugin-pubsub: NatsPubSub over subjects, via the official `nats` (nats.js). Pub/sub only (pair with a KV adapter for state)."
  },
  {
    "name": "@youneed/server-plugin-pubsub-postgres",
    "dir": "server-plugin-pubsub-postgres",
    "cat": "server",
    "desc": "Postgres adapter for @youneed/server-plugin-pubsub + -store: PostgresKV (table) and PostgresPubSub (LISTEN/NOTIFY), via the official `pg` driver."
  },
  {
    "name": "@youneed/server-plugin-pubsub-rabbitmq",
    "dir": "server-plugin-pubsub-rabbitmq",
    "cat": "server",
    "desc": "RabbitMQ adapter for @youneed/server-plugin-pubsub: RabbitMQPubSub over an AMQP exchange, via the official `amqplib`. Pub/sub only (pair with a KV adapter for state)."
  },
  {
    "name": "@youneed/server-plugin-pubsub-redis",
    "dir": "server-plugin-pubsub-redis",
    "cat": "server",
    "desc": "Redis/Valkey adapter — RedisKV (@youneed/server-plugin-store) + RedisPubSub (@youneed/server-plugin-pubsub) over a hand-rolled minimal RESP2 client (zero external deps)."
  },
  {
    "name": "@youneed/server-plugin-pubsub-sqs",
    "dir": "server-plugin-pubsub-sqs",
    "cat": "server",
    "desc": "AWS SQS adapter for @youneed/server-plugin-pubsub: SqsPubSub over SQS queues (channel = queue), pure fetch + SigV4 (no aws-sdk). Long-poll consumer."
  },
  {
    "name": "@youneed/server-plugin-queue",
    "dir": "server-plugin-queue",
    "cat": "server",
    "desc": "@youneed/server plugin: a durable background job queue (retries, backoff, dead-letter, delayed jobs, concurrent workers) persisted to a KV store, with a devtools tab."
  },
  {
    "name": "@youneed/server-plugin-rbac",
    "dir": "server-plugin-rbac",
    "cat": "server",
    "desc": "@youneed/server plugin + controller provider + guard for @youneed/rbac: request-scoped `this.can`, an `authorize(action, resource)` guard, a roles/check introspection API, and a devtools RBAC tab."
  },
  {
    "name": "@youneed/server-plugin-secrets",
    "dir": "server-plugin-secrets",
    "cat": "server",
    "desc": "@youneed/server plugin + controller provider for @youneed/secrets: request-safe `this.secrets`, SAFE introspection routes (names + masked presence probe — values NEVER exposed), and a devtools Secrets tab."
  },
  {
    "name": "@youneed/server-plugin-ssr",
    "dir": "server-plugin-ssr",
    "cat": "server",
    "desc": "@youneed/server plugin: add SSR pages and satellite SSR modules (robots/sitemap/rss/llms/structured-data) to a server from the outside."
  },
  {
    "name": "@youneed/server-plugin-storage",
    "dir": "server-plugin-storage",
    "cat": "server",
    "desc": "@youneed/server plugin: pluggable object/blob storage (memory, filesystem, S3) behind one StorageAdapter contract, with a devtools object-browser tab."
  },
  {
    "name": "@youneed/server-plugin-store",
    "dir": "server-plugin-store",
    "cat": "server",
    "desc": "Distributed key-value contract (KV) + in-process MemoryKV. The backing store is chosen by adapter (redis/postgres/deno via @youneed/server-plugin-pubsub-*)."
  },
  {
    "name": "@youneed/server-upload",
    "dir": "server-upload",
    "cat": "server",
    "desc": "Streaming multipart/form-data file uploads for @youneed/server: web streams, progress, and size/extension/type/name/content guards."
  },
  {
    "name": "@youneed/ssr",
    "dir": "ssr",
    "cat": "ssr",
    "desc": "Server-side rendering + Page entity for @youneed components."
  },
  {
    "name": "@youneed/ssr-plugin-canonical",
    "dir": "ssr-plugin-canonical",
    "cat": "ssr",
    "desc": "SSR page middleware for @youneed: emit <link rel=\"canonical\"> and hreflang alternates per page."
  },
  {
    "name": "@youneed/ssr-plugin-csp",
    "dir": "ssr-plugin-csp",
    "cat": "ssr",
    "desc": "SSR Content-Security-Policy for @youneed: per-request nonce, header builder, and inline-script nonce injection for document responses."
  },
  {
    "name": "@youneed/ssr-plugin-feature-flags",
    "dir": "ssr-plugin-feature-flags",
    "cat": "ssr",
    "desc": "SSR module for @youneed/server-plugin-ssr: evaluate feature flags on the server and inject the snapshot (window.__FLAGS__) into every page for client hydration."
  },
  {
    "name": "@youneed/ssr-plugin-llms",
    "dir": "ssr-plugin-llms",
    "cat": "ssr",
    "desc": "SSR module for @youneed/server-plugin-ssr: serve an llms.txt (and optional llms-full.txt) guide for LLM crawlers."
  },
  {
    "name": "@youneed/ssr-plugin-meta",
    "dir": "ssr-plugin-meta",
    "cat": "ssr",
    "desc": "SSR page middleware for @youneed: emit SEO <meta> + OpenGraph + Twitter Card tags from per-page declarations."
  },
  {
    "name": "@youneed/ssr-plugin-otel",
    "dir": "ssr-plugin-otel",
    "cat": "otel",
    "desc": "@youneed/ssr module: real OpenTelemetry SDK — ssr.render spans per static page render, ssr.render metrics, via the shared @youneed/otel core."
  },
  {
    "name": "@youneed/ssr-plugin-preload",
    "dir": "ssr-plugin-preload",
    "cat": "ssr",
    "desc": "SSR page middleware for @youneed: emit resource hints (<link rel=preload/modulepreload/preconnect/dns-prefetch/prefetch>) per page."
  },
  {
    "name": "@youneed/ssr-plugin-robots",
    "dir": "ssr-plugin-robots",
    "cat": "ssr",
    "desc": "SSR module for @youneed/server-plugin-ssr: generate robots.txt with per-agent allow/disallow rules and sitemap links."
  },
  {
    "name": "@youneed/ssr-plugin-rss",
    "dir": "ssr-plugin-rss",
    "cat": "ssr",
    "desc": "SSR module for @youneed/server-plugin-ssr: serve an RSS 2.0 or Atom feed from a list of items."
  },
  {
    "name": "@youneed/ssr-plugin-sitemap",
    "dir": "ssr-plugin-sitemap",
    "cat": "ssr",
    "desc": "SSR module for @youneed/server-plugin-ssr: generate sitemap.xml from mounted page routes plus explicit entries."
  },
  {
    "name": "@youneed/ssr-plugin-speculation",
    "dir": "ssr-plugin-speculation",
    "cat": "ssr",
    "desc": "SSR page middleware for @youneed/ssr: inject the Speculation Rules API <script> (prefetch/prerender) from a page's declared rules."
  },
  {
    "name": "@youneed/ssr-plugin-structured-data",
    "dir": "ssr-plugin-structured-data",
    "cat": "ssr",
    "desc": "SSR module for @youneed/server-plugin-ssr: inject JSON-LD structured data (schema.org) into page <head>, with typed builders."
  },
  {
    "name": "@youneed/ssr-router",
    "dir": "ssr-router",
    "cat": "ssr",
    "desc": "SSR router for @youneed: an ssr() module adding Error/404 pages (server), plus the @youneed/dom-router for client SPA navigation."
  },
  {
    "name": "@youneed/test",
    "dir": "test",
    "cat": "test",
    "desc": "you need test framework"
  },
  {
    "name": "@youneed/test-devtools",
    "dir": "test-devtools",
    "cat": "test",
    "desc": "Live web-UI devtools reporter for @youneed/test — streams the run to a browser over SSE"
  },
  {
    "name": "@youneed/test-expect-extra",
    "dir": "test-expect-extra",
    "cat": "test",
    "desc": "Extra expect matchers for @youneed/test"
  },
  {
    "name": "@youneed/test-plugin-benchmark",
    "dir": "test-plugin-benchmark",
    "cat": "test",
    "desc": "Benchmark extension for @youneed/test (decorator + plugin + reporter)"
  },
  {
    "name": "@youneed/test-plugin-feature-flags",
    "dir": "test-plugin-feature-flags",
    "cat": "test",
    "desc": "Deterministic feature-flag helpers for @youneed/test: a fresh FeatureFlags fixture that resets overrides between tests, plus a scoped withFlags(...) override helper."
  },
  {
    "name": "@youneed/test-plugin-i18n",
    "dir": "test-plugin-i18n",
    "cat": "test",
    "desc": "Translation parity checks for @youneed/test: assert no missing/extra keys or drifted placeholders across locales."
  },
  {
    "name": "@youneed/test-plugin-otel",
    "dir": "test-plugin-otel",
    "cat": "otel",
    "desc": "@youneed/test plugin: real OpenTelemetry SDK — a span per test case with steps and failure status, test.* metrics, OTLP/HTTP export flushed at teardown."
  },
  {
    "name": "@youneed/test-plugin-rbac",
    "dir": "test-plugin-rbac",
    "cat": "test",
    "desc": "Deterministic RBAC helpers for @youneed/test: a fresh RBAC fixture that resets role tweaks between tests, ergonomic Subject builders, expectCan/expectCannot assertions, and a scoped withRole(...) helper."
  },
  {
    "name": "@youneed/test-reporter-console",
    "dir": "test-reporter-console",
    "cat": "test",
    "desc": "Colored console reporter for @youneed/test"
  },
  {
    "name": "@youneed/test-reporter-html",
    "dir": "test-reporter-html",
    "cat": "test",
    "desc": "HTML report reporter for @youneed/test"
  },
  {
    "name": "@youneed/test-reporter-junit",
    "dir": "test-reporter-junit",
    "cat": "test",
    "desc": "JUnit XML reporter for @youneed/test"
  },
  {
    "name": "@youneed/test-reporter-progress",
    "dir": "test-reporter-progress",
    "cat": "test",
    "desc": "Live, interactive per-lane progress reporter for @youneed/test"
  },
  {
    "name": "@youneed/test-reporter-tap",
    "dir": "test-reporter-tap",
    "cat": "test",
    "desc": "TAP reporter for @youneed/test"
  },
  {
    "name": "@youneed/test-resilience",
    "dir": "test-resilience",
    "cat": "test",
    "desc": "Timeout and retry plugins for @youneed/test"
  },
  {
    "name": "@youneed/test-snapshot",
    "dir": "test-snapshot",
    "cat": "test",
    "desc": "Snapshot testing for @youneed/test"
  },
  {
    "name": "@youneed/ts-plugin",
    "dir": "ts-plugin",
    "cat": "core",
    "desc": "TypeScript language-service plugin: completions inside html`` / css`` for @youneed/dom — custom-element tags, .props and @events."
  },
  {
    "name": "@youneed/vite-plugin",
    "dir": "vite-plugin",
    "cat": "core",
    "desc": "Vite plugin for @youneed components."
  }
];
